apiVersion: v1
kind: ConfigMap
metadata:
  namespace: papertrader
  name: globalconfigmap
data:
  player_initial_lives: "3"
  cluster_name: stargate
  cluster_version: "3.11"
  cluster_dev_mode: "true"
