kind: Cluster
name: "ptc"
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  ipFamily: ipv4
  apiServerAddress: 127.0.0.1
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 8080
    hostPort: 8080
  - containerPort: 8081
    hostPort: 8081
  - containerPort: 8082
    hostPort: 8082
  - containerPort: 8083
    hostPort: 8083
  - containerPort: 9042
    hostPort: 9042