apiVersion: v1
kind: Service
metadata:
  namespace: papertrader
  name: papertrader-api
  labels:
    app.kubernetes.io/name: papertrader-api
    app.kubernetes.io/component: api
spec:
  ports:
  - port: 8083
    name: http
    targetPort: 8083
  selector:
    app.kubernetes.io/name: papertrader-api
    app.kubernetes.io/component: api