apiVersion: v1
kind: Service
metadata:
  name: stargate
  labels:
    app.kubernetes.io/name: stargate
    app.kubernetes.io/component: backend
spec:
  ports:
  - port: 8080
    name: http
    targetPort: 8080
  - port: 8081
    name: auth
    targetPort: 8081
  - port: 8082
    name: data
    targetPort: 8082
  - port: 9042
    name: cas
    targetPort: 9042
  selector:
    app.kubernetes.io/name: stargate
    app.kubernetes.io/component: backend
